-- 조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기
SELECT CONCAT("/home/grep/src/", B.BOARD_ID,"/", FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS B JOIN USED_GOODS_FILE AS F ON B.BOARD_ID = F.BOARD_ID
WHERE B.VIEWS = (
SELECT MAX(VIEWS) FROM USED_GOODS_BOARD )
ORDER BY FILE_ID DESC;
