-- 프로그래머스 과일로 만든 아이스크림 구하기
SELECT F.FLAVOR
FROM FIRST_HALF AS F JOIN ICECREAM_INFO AS I ON F.FLAVOR = I.FLAVOR
WHERE I.INGREDIENT_TYPE LIKE "fruit_based" AND F.TOTAL_ORDER > 3000
ORDER BY F.TOTAL_ORDER desc;
