-- 취소되지 않은 진료 예약 조회하기
SELECT APNT_NO, PT_NAME, P.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT AS A 
JOIN DOCTOR AS D
ON A.MDDR_ID = D.DR_ID 
JOIN PATIENT AS P 
ON A.PT_NO = P.PT_NO
WHERE APNT_CNCL_YN != "Y" AND YEAR(APNT_YMD) = 2022 AND MONTH(APNT_YMD) = 4 AND DAY(APNT_YMD) = 13
ORDER BY APNT_YMD;
