-- 5월 식품들의 총매출 조회하기

SELECT P.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS P JOIN FOOD_ORDER AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE, "%Y-%m") = "2022-05"
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;
